In [ ]:
!pip install --upgrade torch

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

print(torch.__version__)

2.4.1+cu121


# Intro to Tensors

## Creating tensors

In [ ]:
# Scaler tensor

scaler=torch.tensor(6)

print("Scaler Tensor: ",scaler)

Scaler Tensor:  tensor(6)


In [ ]:
# Dimension
scaler.ndim

0

In [ ]:
# get the vector back into python int
scaler.item()

6

In [ ]:
# Vector
lis=[1,3]

vector=torch.tensor(lis)
print("Vector: ",vector)

Vector:  tensor([1, 3])


In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
data=[
    [1,2],
    [3,4]
]

matrix=torch.tensor(data)
print("Matrix: \n",matrix)

Matrix: 
 tensor([[1, 2],
        [3, 4]])


In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR=torch.tensor([[
    [1,2,3],
    [4,6,8],
    [9,10,90]
]])

print("Tensor: \n",TENSOR)

Tensor: 
 tensor([[[ 1,  2,  3],
         [ 4,  6,  8],
         [ 9, 10, 90]]])


In [ ]:
TENSOR.ndim

3

In [ ]:

TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0][0]

tensor([1, 2, 3])

# RANDOM TENSOR
- Random tensor in important in pytorch b/c all the value are fill with random number and change the random nbr after itrating on data.
- `random nbr => itrate on data => update the random nbr`

In [ ]:
# RANDOM TENSOR
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.1516, 0.1184, 0.8745, 0.3853],
        [0.5295, 0.8490, 0.1940, 0.3654],
        [0.5549, 0.9488, 0.9862, 0.3212]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor similar to the shape of images
random_image_tensor=torch.rand(size=(224,224,3)) # Height , Width , Channel(RGB)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones tensor

In [ ]:
# Zeros and ones tensor
zero_tensor=torch.zeros(size=(3,4))
zero_tensor.shape, zero_tensor

(torch.Size([3, 4]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

In [ ]:
# Zeros and ones tensor
onse_tensor=torch.ones(size=(3,4))
onse_tensor.shape, onse_tensor

(torch.Size([3, 4]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

# Tensor Arange

In [ ]:
one_to_one=torch.arange(start=1,end=11,step=2)
one_to_one

tensor([1, 3, 5, 7, 9])

# Tensor Datatypes

In [ ]:
# Float 32 tensor
float_32_tensor=torch.tensor(list(range(1,5)),dtype=None)
float_32_tensor

tensor([1, 2, 3, 4])

In [ ]:
float_32_tensor.dtype

torch.int64

In [ ]:
# Float 32 tensor
float_32_tensor=torch.tensor(list(range(1,5)),dtype=torch.float32)
float_32_tensor

tensor([1., 2., 3., 4.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# torch.dtype, require_grade, to_device
float_32_tensor=torch.tensor(list(range(1,5)),
                             dtype=torch.float32, # Data type of the tensor (float32, int32 and many more)
                             device=None, # Device are 'cpu' and 'cuda'
                             requires_grad=False) # Are used to track the gradient
float_32_tensor, float_32_tensor.dtype

(tensor([1., 2., 3., 4.]), torch.float32)

In [ ]:
# convert the float32 to int32
int32_tensor=float_32_tensor.type(torch.int32)
int32_tensor,int32_tensor.dtype

(tensor([1, 2, 3, 4], dtype=torch.int32), torch.int32)

In [ ]:
# multiply 2 different types of tensors
results=float_32_tensor * int32_tensor
results, results.dtype

(tensor([ 1.,  4.,  9., 16.]), torch.float32)

# Get the information form tensor
- Get the datatypes we use `.dtype`
- Get the device we use `.device`
- Get the shape we use `.shape`

In [ ]:
## Getting informtion from tensors
info_tensor=torch.rand(3,4,dtype=torch.float16)
print(f"Tensor: \n{info_tensor}")

print("*"*50)
print(f"Shape: {info_tensor.shape}")
print("*"*50)

print(f"Datatypes: {info_tensor.dtype}")
print("*"*50)

print(f"Device: {info_tensor.device}")

Tensor: 
tensor([[0.3828, 0.6455, 0.9214, 0.5928],
        [0.7314, 0.4336, 0.9888, 0.9810],
        [0.5352, 0.0381, 0.5249, 0.5913]], dtype=torch.float16)
**************************************************
Shape: torch.Size([3, 4])
**************************************************
Datatypes: torch.float16
**************************************************
Device: cpu


# Tensor Manipulation
- **Tensor Operations include**
  - **Addition**
  - **Substraction**
  - **Multplication**
  - **Division**

In [ ]:
# Create a tensor
tensor=torch.tensor([2,4,6])

print(f"Tensor: {tensor}")
print("*"*50)

tensor_add=tensor+50
print(f"Tensor Add: {tensor_add}")

Tensor: tensor([2, 4, 6])
**************************************************
Tensor Add: tensor([52, 54, 56])


In [ ]:
print(f"Tensor: {tensor}")
print("*"*50)

tensor_sub=tensor-50
print(f"Tensor Add: {tensor_sub}")

Tensor: tensor([2, 4, 6])
**************************************************
Tensor Add: tensor([-48, -46, -44])


In [ ]:
print(f"Tensor: {tensor}")
print("*"*50)

tensor_mul=tensor*50
print(f"Tensor Add: {tensor_mul}")

Tensor: tensor([2, 4, 6])
**************************************************
Tensor Add: tensor([100, 200, 300])


In [ ]:
print(f"Tensor: {tensor}")
print("*"*50)

tensor_div=tensor/10
print(f"Tensor Add: {tensor_div}")

Tensor: tensor([2, 4, 6])
**************************************************
Tensor Add: tensor([0.2000, 0.4000, 0.6000])


# Matrix Multpliplication
- **Two ways of multlipication in neural network**
 - `Element Wise Multplipication`
 - `Matrix Multplplication`

- For more information check out here: https://www.mathsisfun.com/

- **There are 2 main rules for matrix multpliplications**
  - The `Inner dimensions` must match
    - `(3,2) @ (3,2)` won't work
    - `(3,2) @ (2,3)` will work
  - The resultant matrix is the shape of outer dimension
    - `(3,2) @ (2,3)` Result dimension `(3,3)`
  
- Check out for matrix multliplication: http://matrixmultiplication.xyz/

In [ ]:
# Make a random matrix with different inner dimmesion and multpliply
fir=torch.rand(2,3)
sec=torch.rand(2,3)

print(f"First Matrix: \n{fir}")
print("*"*50)
print(f"Second Matrix: \n{sec}")

print("*"*50)
print(f"Result: \n{torch.matmul(fir,sec)}")

First Matrix: 
tensor([[0.3960, 0.7796, 0.4588],
        [0.0629, 0.5610, 0.6458]])
**************************************************
Second Matrix: 
tensor([[0.4340, 0.2165, 0.6226],
        [0.7616, 0.2087, 0.2469]])
**************************************************


RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
# Make a matrix with same inner dimesion and then multpliply
fir=torch.rand(2,3)  # 2-Rows and 3-Columns
sec=torch.rand(3,2)  # 3-Rows and 2-Columns

print(f"First Matrix: \n{fir}")
print("*"*50)
print(f"Second Matrix: \n{sec}")

print("*"*50)
print(f"Result: \n{torch.matmul(fir,sec)}")

First Matrix: 
tensor([[0.1392, 0.4339, 0.9086],
        [0.8320, 0.9049, 0.0947]])
**************************************************
Second Matrix: 
tensor([[0.1305, 0.1554],
        [0.7813, 0.0346],
        [0.4705, 0.7616]])
**************************************************
Result: 
tensor([[0.7847, 0.7286],
        [0.8602, 0.2327]])


In [ ]:
# =====================Element Wise=============================#
# Matrix 1
mat1=torch.tensor([
    [1,4],
    [6,5]
])

# Matrix 2
mat2=torch.tensor([
    [6,5],
    [3,9]
])

print(f"Matrix 1: \n{mat1}")
print("*"*50)
print(f"Matrix 2: \n{mat2}")

result=mat1*mat2
print("*"*50)
print(f"Result: \n{result}")

Matrix 1: 
tensor([[1, 4],
        [6, 5]])
**************************************************
Matrix 2: 
tensor([[6, 5],
        [3, 9]])
**************************************************
Result: 
tensor([[ 6, 20],
        [18, 45]])


In [ ]:
# =====================Matrix Multliplication=============================#
# Matrix 1
mat1=torch.tensor([
    [1,4],
    [6,5]
])

# Matrix 2
mat2=torch.tensor([
    [6,5],
    [3,9]
])

print(f"Matrix 1: \n{mat1}")
print("*"*50)
print(f"Matrix 2: \n{mat2}")

result=torch.matmul(mat1,mat2)
# Short version is torch.mm

print("*"*50)
print(f"Result: \n{result}")

Matrix 1: 
tensor([[1, 4],
        [6, 5]])
**************************************************
Matrix 2: 
tensor([[6, 5],
        [3, 9]])
**************************************************
Result: 
tensor([[18, 41],
        [51, 75]])


In [ ]:
fir=torch.rand(2,3)
sec=torch.rand(2,3)

print(f"First Matrix: \n{fir}")
print("*"*50)
print(f"Second Matrix: \n{sec}")

print("*"*50)
print(f"Result: \n{torch.matmul(fir,sec)}")

First Matrix: 
tensor([[0.7468, 0.8667, 0.8697],
        [0.2153, 0.0167, 0.7238]])
**************************************************
Second Matrix: 
tensor([[0.9347, 0.8397, 0.4826],
        [0.9845, 0.6291, 0.7613]])
**************************************************


RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
# Now we will fix the issue using by applying the transpose
fir=torch.rand(2,3)
sec=torch.rand(2,3)

print(f"First Matrix: \n{fir}")
print("*"*50)
print(f"Second Matrix: \n{sec}")

print("*"*50)
print(f"Result: \n{torch.matmul(fir,sec.T)}")

First Matrix: 
tensor([[0.2238, 0.2200, 0.8841],
        [0.2723, 0.0309, 0.4829]])
**************************************************
Second Matrix: 
tensor([[0.1751, 0.1410, 0.1982],
        [0.0201, 0.8578, 0.9978]])
**************************************************
Result: 
tensor([[0.2454, 1.0754],
        [0.1478, 0.5139]])


# Tensor Aggreation
- Tensor Aggreeation are `min`,`max`,`Mean` , `Medain` like that

In [ ]:
tensor_a= torch.arange(start=1,end=100,step=2,dtype=torch.float32)
print(f"Tensor: {tensor_a}")

Tensor: tensor([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25., 27.,
        29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51., 53., 55.,
        57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77., 79., 81., 83.,
        85., 87., 89., 91., 93., 95., 97., 99.])


In [ ]:
# Min
tensor_a.min(),  min(tensor_a)

(tensor(1.), tensor(1.))

In [ ]:
# Max
tensor_a.max(),  max(tensor_a)

(tensor(99.), tensor(99.))

In [ ]:
# Mean
torch.mean(tensor_a),tensor_a.mean()

(tensor(50.), tensor(50.))

In [ ]:
# Median
torch.median(tensor_a),tensor_a.median()

(tensor(49.), tensor(49.))

In [ ]:
# Sum
torch.sum(tensor_a),tensor_a.sum()

(tensor(2500.), tensor(2500.))

# Positional max and min
- Position min and max show the index

In [ ]:
tensor_b=torch.arange(start=1,end=50,step=5,dtype=torch.float32)
print(f"Tensor: {tensor_b}")

Tensor: tensor([ 1.,  6., 11., 16., 21., 26., 31., 36., 41., 46.])


In [ ]:
# Argmin
tensor_b.argmin()

tensor(0)

In [ ]:
# Argmax
tensor_b.argmax()

tensor(9)

# Reshaping, Stacking, Squeezing and Unsqueezing Tensors
* `Reshape` => Change the shape of tensor
* `Stacking` => Stack multliply tensors on top of each others
  * Learn More About Stcking: https://pytorch.org/docs/stable/generated/torch.stack.html
* `Squeeze` It can remove all the single dimensions
  * More about squeeze: https://pytorch.org/docs/main/generated/torch.squeeze.html

* `UnSqueeze` It can add the single dimensions
  * More about squeeze: https://pytorch.org/docs/main/generated/torch.unsqueeze.html

In [ ]:
import torch

In [ ]:
# Make a tensors
x=torch.arange(1,13)

x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [ ]:
# Reshape the tensors
x_reshape=x.reshape(12,1)
x_reshape

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])

In [ ]:
# Reshape the tensors
x_reshape=x.reshape(3,4)
x_reshape

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [ ]:
# Reshape the tensors
x_reshape=x.reshape(4,3)
x_reshape

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
# Reshape the tensors
x_reshape=x.reshape(2,6)
x_reshape

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [ ]:
# Reshape the tensors
x_reshape=x.reshape(6,2)
x_reshape

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

In [ ]:
# Reshape the tensors
x_reshape=x.reshape(2,6)
x_reshape

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

# Note
* **Reshape and view are same means both are doing the same thing**

# Stacking
- Syntax: `torch.stack([tensor1,tensor2,......],dim=?)`
  * `dim` should be depend upon the dimension of the tensor you want to stack.
- We can also use `hstack` for stack the tensors `horizentally`
- We can also use `vstack` for stack the tensors `vertically`

In [ ]:
# Tensor1
TENSOR1=torch.arange(1,11).reshape(2,5)

# Tensor2
TENSOR2=torch.arange(11,21).reshape(2,5)

TENSOR1, TENSOR2

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 tensor([[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]))

In [ ]:
# Stack the tensors on top of each others
stack_tensor=torch.stack([TENSOR1,TENSOR1])
stack_tensor

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]])

In [ ]:
# We can add all the tensors as we want
stack_tensor=torch.stack([TENSOR1,TENSOR2,TENSOR1,TENSOR2],dim=0)
stack_tensor

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]])

In [ ]:
# We can add all the tensors as we want
stack_tensor=torch.stack([TENSOR1,TENSOR2,TENSOR1,TENSOR2],dim=1)
stack_tensor

tensor([[[ 1,  2,  3,  4,  5],
         [11, 12, 13, 14, 15],
         [ 1,  2,  3,  4,  5],
         [11, 12, 13, 14, 15]],

        [[ 6,  7,  8,  9, 10],
         [16, 17, 18, 19, 20],
         [ 6,  7,  8,  9, 10],
         [16, 17, 18, 19, 20]]])

In [ ]:
# Note that if we can stack the tensors tensors should be the same shape
stack_tensor=torch.stack([TENSOR1,x_reshape])
stack_tensor

RuntimeError: stack expects each tensor to be equal size, but got [2, 5] at entry 0 and [6, 2] at entry 1

In [ ]:
# Stack horizentally
h_stack=torch.hstack([TENSOR1,TENSOR2])
h_stack

tensor([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
        [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [ ]:
# Stack vertically
v_stack=torch.vstack([TENSOR1,TENSOR2])
v_stack

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

# Squeezing
- Squeezing are used to remove the extra dimensions

In [ ]:
# Squezze
x=torch.arange(1,10).reshape(1,9)

x_squeeze=x.squeeze()

print("============Squeeze==> Squeeze can remove all the single(1) dimensions===================\n")

print("X: ",x)
print("Shape of X: ",x.shape)
print("x_squeeze: ",x_squeeze)
print("Shape of x_squeeze: ",x_squeeze.shape)

print("\n=====================================")

============Squeeze==> Squeeze can remove all the single(1) dimensions===================

X:  tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Shape of X:  torch.Size([1, 9])
x_squeeze:  tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Shape of x_squeeze:  torch.Size([9])



# Unsqueeze
- It is similar to squeeze but i can add the extra dimensions

In [ ]:
# Squezze
x=torch.arange(1,10).reshape(1,9)

# Add the extra dimensions
x_unsqueeze=x.unsqueeze(dim=0)

print("============UnSqueeze==> Squeeze can add the dimensions===================\n")

print("X: ",x)
print("Shape of X: ",x.shape)
print("x_unsqueeze: ",x_unsqueeze)
print("Shape of x_unsqueeze: ",x_unsqueeze.shape)

print("\n=====================================")

============UnSqueeze==> Squeeze can add the dimensions===================

X:  tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Shape of X:  torch.Size([1, 9])
x_unsqueeze:  tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])
Shape of x_unsqueeze:  torch.Size([1, 1, 9])



# Indexing

In [ ]:
# Creating a tensor
x=torch.zeros(4,4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# let's start indexing and also apply some changes
x[0]

tensor([0., 0., 0., 0.])

In [ ]:
# Chage the value of 2 row and 2 element witj -100
x[1][1]=-100

In [ ]:
x

tensor([[   0.,    0.,    0.,    0.],
        [   0., -100.,    0.,    0.],
        [   0.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.]])

In [ ]:
# Now get the value we can change
x[1][1]

tensor(-100.)

In [ ]:
# make another tenor
x=torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Now the challange is to get the only [3,6,9] value
x[0][:,2]

tensor([3, 6, 9])

# Pytorch and Numpy
- Numpy is a popular scientific python numerical computing library
- And because of this pytorch has functionality to interact with it.
  * Data in `Numpy`, want in `pytorch` tensors=> `torch.from_numpy(n_dayarray)` and convert this into `pytorch tensors`
  * From `Pytorch -> Numpy` -> `torch.Tensor.numpy()`

# Numpy `Array` => `Tensors`

In [ ]:
import numpy as np

In [ ]:
# Make a numpy array
array1=np.arange(1,10)

# convert the array into pytorch tensors
tensor1=torch.from_numpy(array1)

print(f"Numpy Array:\n{array1}\n")
print(f"Torch Tensors:\n{tensor1}")

Numpy Array:
[1 2 3 4 5 6 7 8 9]

Torch Tensors:
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


# `Tensor` => `Array`

In [ ]:
# use the previous tensor
tensor1

# convert the tensor back into numpy array
back_array=tensor1.numpy()

print(f"Torch Tensors:\n{tensor1}\n")
print(f"Numpy Array:\n{back_array}")

Torch Tensors:
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

Numpy Array:
[1 2 3 4 5 6 7 8 9]


# Reprodubility (trying to take random out of random)
**In short how a neural network learn**

- `start with random number`===>`look at the data`===> `Update the values`==> `And try to make the better representation of nbrs` ===> `again again and again`

- To reduce the randomness of neural network and pytorch comes with **random seed**

Get more detail check it out: https://pytorch.org/docs/stable/notes/randomness.html

In [ ]:
# make a random tensors
torch.rand(3,3)

tensor([[0.5823, 0.1702, 0.7787],
        [0.2556, 0.1169, 0.8104],
        [0.5156, 0.6031, 0.6797]])

In [ ]:
torch.rand(3,3)

tensor([[0.7754, 0.1965, 0.4142],
        [0.2112, 0.1339, 0.1210],
        [0.1779, 0.3437, 0.6792]])

In [ ]:
tensor_1=torch.rand(3,3)

tensor_2=torch.rand(3,3)

print(f"Tensor 1:\n{tensor_1}\n")
print(f"Tensor 2:\n{tensor_2}\n")
print(f"Does Tensor 1 equal Tensor 2:\n{tensor_1==tensor_2}")

Tensor 1:
tensor([[0.3944, 0.8780, 0.4316],
        [0.6334, 0.5795, 0.3930],
        [0.6524, 0.7860, 0.6040]])

Tensor 2:
tensor([[0.1595, 0.5068, 0.7265],
        [0.4217, 0.6602, 0.0833],
        [0.1002, 0.5634, 0.9204]])

Does Tensor 1 equal Tensor 2:
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


# Observation
- we can see that evertime we can run the above cell it will give the different random value it is not good.
- We can also see that we can run the 2 cell with same code but the result of both the same code is different
- To controll the randomness we use `radom seed`

In [ ]:
# use random seed to control the randomness
random_seed=42
torch.manual_seed(random_seed)

# make a tensor1
tensor1=torch.rand(3,3)

# make a tensor2 and also set the random seed of each tensor
torch.manual_seed(random_seed)
tensor2=torch.rand(3,3)

print(f"Tensor 1:\n{tensor1}\n")
print(f"Tensor 2:\n{tensor2}\n")
print(f"Does Tensor 1 equal Tensor 2:\n{tensor1==tensor2}")

Tensor 1:
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

Tensor 2:
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

Does Tensor 1 equal Tensor 2:
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


# Different Way to accessing `GPU`
* Runniny pytorch tensor on `GPU` for fastest processing

## Getting a `GPU`
1. Easiest - Use google colab for free GPU
2. Use your own
3. Use cloud computing - GCP, AWS, Azure

**For 2 and 3 check out this: https://pytorch.org/**
**If want to train the machine learning model using skorch check out this: https://github.com/skorch-dev/skorch**

# skorch(https://github.com/skorch-dev/skorch)
- `skorch` is a pytorch frame work that support to train the machine learnings models

In [ ]:
# Check out the GPU detail
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


# Check out the pytoch access using `pytorch`

In [ ]:
import torch
torch.cuda.is_available()

False

In [ ]:
# setup the device agnestice code
if torch.cuda.is_available():
  device="cude"
else:
  device="cpu"

device

'cpu'

In [ ]:
# Count the nbr of devices
torch.cuda.device_count()

0

In [ ]:
# Excercise and Extra Curriculum